### ISSUE TITLE
Problemas con DV

### ISSUE THREAD

**Issue by mbalmaceda** [kadumedia/jQuery.rut.chileno#1]
Cuando se utiliza un Rut con dígito verificador "K" y este se pone en mayúscula, al momento de hacer el submit del formulario este envía el siguiente error: "Utiliza un formato que coincida con el solicitado".

P.D: Esta bkn el plugin, solo encontré ese error, saludos!

**Comment by PabloCgs** [comment]
es muy bueno. pero si ingreso un  Rut formateado no lo valida (da como que fuera un DV erroneo)

**Comment by kadumedia** [comment]
Vale estimado, había hecho hace tiempo el plugin para probar, le mande un arreglo a formato con miles y k K

Saludos y gracias 👍
